---
- name: Make sure autorestic user exists
  ansible.builtin.user:
    name: "{{ autorestic_user }}"
  become: true
  register: autorestic_user_register
  tags:
    - autorestic_cron
    - autorestic_check

- name: Set autorestic_user_home variable
  ansible.builtin.set_fact:
    autorestic_user_home: "{{ autorestic_user_register.home }}"
  tags:
    - autorestic_cron
    - autorestic_check

- name: Copy autorestic config file
  ansible.builtin.copy:
    content: "{{ autorestic_config | to_nice_yaml }}"
    dest: "{{ autorestic_config_path }}"
    owner: "{{ autorestic_config_owner }}"
    group: "{{ autorestic_config_group }}"
    mode: "{{ autorestic_config_mode }}"
  when: autorestic_config is defined
  become: true

- name: Add autorestic to cron
  ansible.builtin.cron:
    name: "autorestic cron"
    minute: "{{ autorestic_cron_minute }}"
    hour: "{{ autorestic_cron_hour }}"
    month: "{{ autorestic_cron_month }}"
    weekday: "{{ autorestic_cron_weekday }}"
    user: "{{ autorestic_user }}"
    job: "{{ autorestic_install_path }} -c {{ autorestic_config_path }} --restic-bin {{ autorestic_restic_install_path }} --ci cron"
  become: true
  when: autorestic_cron | bool
  tags: autorestic_cron

- name: Run autorestic check
  ansible.builtin.command:
    cmd: "{{ autorestic_install_path }} -c {{ autorestic_config_path }} --restic-bin {{ autorestic_restic_install_path }} check"
  become: true
  changed_when: '"Everything is fine." not in autorestic_check_register.stdout'
  register: autorestic_check_register
  tags: autorestic_check
  when: '"autorestic_check" in ansible_run_tags'
