---
- name: Make sure autorestic user exists
  user:
    name: "{{ autorestic_user }}"
  register: autorestic_user_register
  become: true

- name: Set autorestic_user_directory variable
  set_fact:
    autorestic_user_directory: "{{ autorestic_user_register.home }}"

- name: Copy autorestic config file
  copy:
    content: "{{ autorestic_config_yaml | to_nice_yaml }}"
    dest: "{{ autorestic_config_path }}"
    owner: "{{ autorestic_config_owner }}"
    group: "{{ autorestic_config_group }}"
    mode: "{{ autorestic_config_mode }}"
  when: autorestic_config_yaml != "CHANGEME"
  become: true

- name: Add autorestic to cron
  cron:
    name: "autorestic cron"
    minute: "{{ autorestic_cron_minute }}"
    hour: "{{ autorestic_cron_hour }}"
    month: "{{ autorestic_cron_month }}"
    weekday: "{{ autorestic_cron_weekday }}"
    user: "{{ autorestic_user }}"
    job: "{{ autorestic_install_path }} -c {{ autorestic_config_path }} --ci cron"
  become: true
  ignore_errors: true
  when: autorestic_cron | bool
  tags: autorestic_cron
