---
- name: Install anacron packages
  package:
    name: "{{ autorestic_cron_packages }}"
    state: present
  become: true
  when: autorestic_cron_hourly != "CHANGEME" 
    or autorestic_cron_daily != "CHANGEME"
    or autorestic_cron_weekly != "CHANGEME"
    or autorestic_cron_monthly != "CHANGEME"

- name: Set ansible_cron_list variable
  set_fact:
    ansible_cron_list:
      - time: hourly
        content: "{{ autorestic_cron_hourly }}"
      - time: daily
        content: "{{ autorestic_cron_daily }}"
      - time: weekly
        content: "{{ autorestic_cron_weekly }}"
      - time: monthly
        content: "{{ autorestic_cron_monthly }}"

- name: Copy cron scripts
  copy:
    content: "{{ item.content }}"
    dest: "/etc/cron.{{ item.time }}/autorestic_{{ autorestic_user }}"
    owner: "root"
    group: "root"
    mode: "0755"
  become: true
  loop: "{{ ansible_cron_list | rejectattr('content', 'equalto', 'CHANGEME') }}"

- name: Remove cron scripts
  file:
    path: "/etc/cron.{{ item.time }}/autorestic_{{ autorestic_user }}"
    state: absent
  become: true
  loop: "{{ ansible_cron_list | selectattr('content', 'equalto', 'CHANGEME') }}"
