---
- name: Install anacron
  apt:
    cache_valid_time: 3600
    name: anacron
    state: present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- set_fact:
    ansible_cron_list:
      - time: hourly
        content: "{{ autorestic_cron_hourly }}"
      - time: daily
        content: "{{ autorestic_cron_daily }}"
      - time: weekly
        content: "{{ autorestic_cron_weekly }}"
      - time: monthly
        content: "{{ autorestic_cron_monthly }}"

- name: Copy cron
  copy:
    content: "{{ item.content }}"
    dest: "/etc/cron.{{ item.time }}/autorestic_{{ autorestic_user }}"
    owner: "root"
    group: "root"
    mode: "0755"
  become: true
  loop: "{{ ansible_cron_list | rejectattr('content', 'equalto', 'CHANGEME') }}"

- name: Remove cron
  file:
    path: "/etc/cron.{{ item.time }}/autorestic_{{ autorestic_user }}"
    state: absent
  become: true
  loop: "{{ ansible_cron_list | selectattr('content', 'equalto', 'CHANGEME') }}"
