---
- name: Add autorestic to cron
  cron:
    name: "autorestic cron"
    minute: "{{ autorestic_cron_minute }}"
    hour: "{{ autorestic_cron_hour }}"
    month: "{{ autorestic_cron_month }}"
    weekday: "{{ autorestic_cron_weekday }}"
    user: "{{ autorestic_user }}"
    job: "{{ autorestic_install_path }} --ci cron"
  ignore_errors: true
  become: true
  when: autorestic_cron

- name: Remove autorestic from cron
  cron:
    name: "autorestic cron"
    user: "{{ autorestic_user }}"
    state: absent
  ignore_errors: true
  become: true
  when: not autorestic_cron
