---
- name: Install dependencies
  ansible.builtin.package:
    name: "{{ autorestic_packages }}"
    state: present
  become: true
  tags: autorestic, autorestic_restic_install, autorestic_install

- ansible.builtin.import_tasks: install-restic.yml
  tags: autorestic, autorestic_restic_install

- ansible.builtin.import_tasks: install-autorestic.yml
  tags: autorestic, autorestic_install

- ansible.builtin.import_tasks: configure.yml
  tags: autorestic, autorestic_configure
