---
- name: Install dependencies
  package:
    name: "{{ autorestic_packages }}"
    state: present
  become: true

- import_tasks: install-restic.yml
  when: autorestic_restic_install
  tags: autorestic_restic_install

- import_tasks: install-autorestic.yml
  when: autorestic_install
  tags: autorestic_install

- import_tasks: user.yml
  tags: autorestic_user
