---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: Install dependencies
  package:
    name: "{{ autorestic_packages }}"
    state: present
  become: true

- import_tasks: install-restic.yml
  when: autorestic_restic_install

- import_tasks: install-autorestic.yml
  when: autorestic_autorestic_install

- import_tasks: user.yml

- import_tasks: cron.yml
