---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: debian11
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
  - name: rockylinux8
    image: docker.io/geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
