---
autorestic_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEAy6FTZCtySHh5llbKxBR/D4bYg9Tx1LxaHBnrHXlyizGpDkQwDxiS
  xLTe2bBNjs6kcgQn/Fb4wREG1lDXhLfnygDxmBDMtnilkLO/FgQ3jUKGF6KqotWyqa4nb8
  LDbje8jLU9VfHowhkicFvqxH+c5XzRXf1bp7RDU6XBVRvxR22v5yM406kL1xxm4zy+v6OA
  gkBxGekUB8uDefjdqjDPMb6T4lKNgQu6KtTfzX4N+nPiIKED2hLPQgqn9L2CHPI88SMtKU
  39q+vTGl23ne7+c7kcQdWf5UitAOooxi0HlCEaQD+O/q9B4VPFDTIr1CqOqijj+6TXE0Eu
  VwHVH/kSYMf/EELQenTDjhANHRVskNc1AhdWDD7X2TmfKoZDrJgGyPf3AEdXJ2xSbXB7z9
  bC+8KAh/Vkl5sFV93S0UH4VAE+KMuolR4xhWlPnLS12qJrQo03I22iRvibzeEEia6fQ9ha
  XfCzDEXgE6/ZwokU6xbySMMxUjvtGOcN/kP6CBTTAAAFiDzSjew80o3sAAAAB3NzaC1yc2
  EAAAGBAMuhU2Qrckh4eZZWysQUfw+G2IPU8dS8WhwZ6x15cosxqQ5EMA8YksS03tmwTY7O
  pHIEJ/xW+MERBtZQ14S358oA8ZgQzLZ4pZCzvxYEN41ChheiqqLVsqmuJ2/Cw243vIy1PV
  Xx6MIZInBb6sR/nOV80V39W6e0Q1OlwVUb8Udtr+cjONOpC9ccZuM8vr+jgIJAcRnpFAfL
  g3n43aowzzG+k+JSjYELuirU381+Dfpz4iChA9oSz0IKp/S9ghzyPPEjLSlN/avr0xpdt5
  3u/nO5HEHVn+VIrQDqKMYtB5QhGkA/jv6vQeFTxQ0yK9Qqjqoo4/uk1xNBLlcB1R/5EmDH
  /xBC0Hp0w44QDR0VbJDXNQIXVgw+19k5nyqGQ6yYBsj39wBHVydsUm1we8/WwvvCgIf1ZJ
  ebBVfd0tFB+FQBPijLqJUeMYVpT5y0tdqia0KNNyNtokb4m83hBImun0PYWl3wswxF4BOv
  2cKJFOsW8kjDMVI77RjnDf5D+ggU0wAAAAMBAAEAAAGAB5pjcbcJklklOQ7OjVmykNLZHL
  sDuIy71JbHJ5eURkw5YrX7EWU6fau/MmOZ0b43d6ZeE9bvfM308mWcVnFDb1BvtNzTt/Bz
  Rh7gAKNxq42TUiiZtHDENf+xq0ObZm8gVCSkQKRCq5Siq41TC7k0E4GAk8DU/kMFzIbA3D
  up25/l1HyFL6n9Li/6S3vGJ4OkVbiwQGZqgAwCQbigFi2yXsod3XJ1pB7a+aRvIs4VGYfg
  JpW8fhT7thyNvt6gkBIfUVdEVWCNGkPOYIMUX5BzweEhIS9uV+tDqRbc36B9tmfDW9k5Xi
  fMBev8EOexfCzOjyjM3I0y/U2M5vTUMu5Wnfhr70rquGJ7zFJY3Z5g8Bh5FGEd0xrMg40B
  /TR0IRl2Mtvqeh40rihv7GGxlEJX/ryIKlD4FycJt6Z0onaGbemTw1tUr2p3SgtGySit/n
  WGigtd/lZcCoc+sXAJQ8fqaDMBQZaoRTq99jrhEKrFQtK8wFaV2FBN8jC7G6TAKVghAAAA
  wQCV2wBxcPXND2x5GZCX76bPTba9QTPqoyBfEPGqjhHzofhHNQEVtP29ViVEC5iYF7A9ue
  DTxVNaRit82cIoYqu68kSaicHuopKekuDFdv/aVFSQ4S/u5l7bpQEKCpNC95SnXdhoHdOj
  K9A71ftp1NVphLexheQoFToZwXUkuohhZpxZDJe+HcNpbNU9DXrcSKTZmHGn4mTsAmQBBl
  bsGK0/yD2WSAXpe02M4F3ByH4KytJ6xGyh9IZLvVTj3RahKHAAAADBAOp4X2M00uOcvnF4
  QJoubPBidNS8BvhOFHTgJywoTVjEozsE9qYZraHwG68CKEG/AiJ2zHqkgwug3rjHODSzK5
  88pqgpwUNvvGXaVr1SFmOl0vlpjAg4xY8NAtFng0qTaMpmS2NTLni0oknLxl3GKyMU7DW6
  tQQnnfYpdjqU23hzfm04k6VyX1iWEJCCy8x9ETlDfg+ESpmZpkjKPzrJNIQ/NNv1gXYjGJ
  bUdvthlu0DQVYcT11I4FE9sAnM9Cg0AwAAAMEA3lQBSHbaxN22XaDY+WnOeHhXC/S3cABk
  1CuydZLDWC+byCz43l+T28rQ7M6S6YlJyZE9VrqzY4dj9y6rlzVrRkzl/AsKDp2ldt4F4y
  M2iEWpFbxPRpmfYfj6RdL5Ie4X1ziAMXCSGWpd7bNcAI/9vGBG63r7uZ92Klf0SwVRHu1M
  jikZdhbgPsKhPQC6VcE7iGiUzmiErLabDwDvzVw+RhgAGNlquD1v0iMfc5TuFKyv5M6eR5
  T4pDrb+vdODQrxAAAADGd1cm5haW5AbWF5bwECAwQFBg==
  -----END OPENSSH PRIVATE KEY-----

autorestic_key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLoVNkK3JIeHmWVsrEFH8PhtiD1PHUvFocGesdeXKLMakORDAPGJLEtN7ZsE2OzqRyBCf8VvjBEQbWUNeEt+fKAPGYEMy2eKWQs78WBDeNQoYXoqqi1bKpridvwsNuN7yMtT1V8ejCGSJwW+rEf5zlfNFd/VuntENTpcFVG/FHba/nIzjTqQvXHGbjPL6/o4CCQHEZ6RQHy4N5+N2qMM8xvpPiUo2BC7oq1N/Nfg36c+IgoQPaEs9CCqf0vYIc8jzxIy0pTf2r69MaXbed7v5zuRxB1Z/lSK0A6ijGLQeUIRpAP47+r0HhU8UNMivUKo6qKOP7pNcTQS5XAdUf+RJgx/8QQtB6dMOOEA0dFWyQ1zUCF1YMPtfZOZ8qhkOsmAbI9/cAR1cnbFJtcHvP1sL7woCH9WSXmwVX3dLRQfhUAT4oy6iVHjGFaU+ctLXaomtCjTcjbaJG+JvN4QSJrp9D2Fpd8LMMReATr9nCiRTrFvJIwzFSO+0Y5w3+Q/oIFNM= test@test

autorestic_config_yaml:
  locations:
    home:
      from: "{{ autorestic_user_directory }}"
      to: local
  backends:
    local:
      type: local
      path: /backup
      key: 123
