---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Get restic version
      ansible.builtin.shell: |
        set -o pipefail
        {{ autorestic_restic_install_path }} version | cut -f2 -d ' '
      args:
        executable: /bin/bash
      register: autorestic_restic_version_register
      changed_when: false

    - name: Assert restic version is correct
      ansible.builtin.assert:
        that: autorestic_restic_version_register.stdout == autorestic_restic_download_version

    - name: Get autorestic version
      ansible.builtin.shell: |
        set -o pipefail
        {{ autorestic_install_path }} --version | cut -f3 -d ' '
      args:
        executable: /bin/bash
      register: autorestic_version_register
      changed_when: false

    - name: Assert autorestic version is correct
      ansible.builtin.assert:
        that: autorestic_version_register.stdout == autorestic_download_version
